import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useContext, useEffect } from "react";
import { AuthContext } from "../../context/authContext";
import { Container } from "@material-ui/core";

const UserHome: NextPage = () => {
  const { currentUser } = useContext(AuthContext);
  console.log("user:", currentUser);
  return (
    <div>
      <Head>
        <title>入出場管理システム</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <h2>ユーザー名:{currentUser?.displayName}</h2>
      </Container>
    </div>
  );
};

export default UserHome;
