import type { NextPage } from "next";
import Head from "next/head";
import Router from "next/router";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  useEffect(() => {
    Router.push("/login");
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>入出場管理システム</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>hello world</p>
    </div>
  );
};

export default Home;
